# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDgzMzQ5ZjgxZGIxMzhjNGI5MmQ0NWJmOTI3MmU3NjhjMzA5MTYzYzRiMDkyOTk5ODIxZTMzMTgxNzRmZTA4NjNlZDIwYmVlNzI5ZDI1YWY1OGM0ZGM4NTdiYTFhMzFjZDBiN2M4ZDVjYmMzNjQ1MGEzODk4MDEwZWM2NDk4Zjk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
